import { json, supabaseAdmin } from '../_lib/supabase-admin.js'

/** POST /api/booth/session — creates a session. Tokens are generated by Postgres. */
export async function POST(): Promise<Response> {
  const { data, error } = await supabaseAdmin
    .from('sessions')
    .insert({})
    .select('secure_token, booth_token')
    .single()

  if (error || !data) return json({ error: 'Could not create session' }, 500)

  // The internal session id is intentionally never returned.
  return json({ boothToken: data.booth_token, secureToken: data.secure_token })
}
